var lesson17 = [
  {
    lesson: 17,
    french: "amande",
    english: "almond",
    spanish: "almendra",
  },
  {
    lesson: 17,
    french: "abricot",
    english: "apricot",
    spanish: "albaricoque",
  },
  {
    lesson: 17,
    french: "asperges",
    english: "asparagus",
    spanish: "espárragos",
  },
  {
    lesson: 17,
    french: "betterave",
    english: "beet",
    spanish: "remolacha",
  },
  {
    lesson: 17,
    french: "poivron",
    english: "pepper",
    spanish: "pimienta",
  },
  {
    lesson: 17,
    french: "fèves",
    english: "beans",
    spanish: "havas",
  },
  {
    lesson: 17,
    french: "brocoli",
    english: "brocolli",
    spanish: "brocolí",
  },
  {
    lesson: 17,
    french: "choux",
    english: "cabbage",
    spanish: "repollo",
  },
  {
    lesson: 17,
    french: "melon",
    english: "mellon",
    spanish: "melón",
  },
  {
    lesson: 17,
    french: "chou-fleur",
    english: "cauliflower",
    spanish: "coliflor",
  },
  {
    lesson: 17,
    french: "céleri",
    english: "celery",
    spanish: "apio",
  },
  {
    lesson: 17,
    french: "cerise",
    english: "cherry",
    spanish: "cereza",
  },
  {
    lesson: 17,
    french: "châtaigne",
    english: "chestnut",
    spanish: "castaña",
  },

  {
    lesson: 17,
    french: "chili",
    english: "chili",
    spanish: "chile",
  },
  {
    lesson: 17,
    french: "pois-chiches",
    english: "chickpeas",
    spanish: "garbanzos",
  },
  {
    lesson: 17,
    french: "noix de coco",
    english: "coconut",
    spanish: "coco",
  },
  {
    lesson: 17,
    french: "myrtille",
    english: "blueberry",
    spanish: "arándano",
  },
  {
    lesson: 17,
    french: "concombre",
    english: "cucumber",
    spanish: "pepino",
  },
  {
    lesson: 17,
    french: "datte",
    english: "date",
    spanish: "dátil",
  },
  {
    lesson: 17,
    french: "aubergine",
    english: "eggplant",
    spanish: "berenjena",
  },
  {
    lesson: 17,
    french: "figue",
    english: "fig",
    spanish: "higo",
  },

  {
    lesson: 17,
    french: "raisin",
    english: "grape",
    spanish: "uva",
  },
  {
    lesson: 17,
    french: "pamplemousse",
    english: "grapefruit",
    spanish: "toronja",
  },
  {
    lesson: 17,
    french: "noisette",
    english: "hazelnut",
    spanish: "avellana",
  },
  {
    lesson: 17,
    french: "lentilles",
    english: "lentils",
    spanish: "lentejas",
  },
  {
    lesson: 17,
    french: "menthe",
    english: "mint",
    spanish: "menta",
  },

  {
    lesson: 17,
    french: "pêche",
    english: "peaches",
    spanish: "durazno",
  },
  {
    lesson: 17,
    french: "nouilles",
    english: "noodles",
    spanish: "fideos",
  },
  {
    lesson: 17,
    french: "olive",
    english: "olive",
    spanish: "aceituna",
  },{
    lesson: 17,
    french: "persil",
    english: "parsley",
    spanish: "perejil",
  },
  {
    lesson: 17,
    french: "cacahuète/arachide",
    english: "peanut",
    spanish: "mani",
  },
  {
    lesson: 17,
    french: "poire",
    english: "pear",
    spanish: "pera",
  },
  {
    lesson: 17,
    french: "petits pois",
    english: "peas",
    spanish: "arvejas",
  },
  {
    lesson: 17,
    french: "cornichon",
    english: "pickles",
    spanish: "pepinillos",
  },
  {
    lesson: 17,
    french: "prune",
    english: "prune",
    spanish: "ciruela",
  },
  {
    lesson: 17,
    french: "citrouille",
    english: "pumpkin",
    spanish: "calabaza",
  },
  {
    lesson: 17,
    french: "radis",
    english: "radish",
    spanish: "rábano",
  },
  {
    lesson: 17,
    french: "épinards",
    english: "spinach",
    spanish: "espinaca",
  },
  {
    lesson: 17,
    french: "navets",
    english: "turnips",
    spanish: "nabos",
  },
  {
    lesson: 17,
    french: "noix",
    english: "nut",
    spanish: "nuez",
  },
  {
    lesson: 17,
    french: "pastèque",
    english: "watermelon",
    spanish: "pastilla",
  },
  {
    lesson: 17,
    french: "pâtes",
    english: "pasta",
    spanish: "pasta",
  },
  {
    lesson: 17,
    french: "haricots",
    english: "beans",
    spanish: "fríjoles",
  },
  {
    lesson: 17,
    french: "viande hachée",
    english: "ground meat",
    spanish: "carne molida",
  },
  {
    lesson: 17,
    french: "banane plantain",
    english: "plantain",
    spanish: "plátano",
  },
  {
    lesson: 17,
    french: "",
    english: "",
    spanish: "",
  },
  {
    lesson: 17,
    french: "",
    english: "",
    spanish: "",
  },
  {
    lesson: 17,
    french: "",
    english: "",
    spanish: "",
  },
  {
    lesson: 17,
    french: "",
    english: "",
    spanish: "",
  },
  {
    lesson: 17,
    french: "",
    english: "",
    spanish: "",
  },


];
