var lesson10 = [
  {
    lesson: 10,
    french: "au sujet de/à propos de",
    english: "about",
    spanish: "sobre/a cerca de",
  },
  {
    lesson: 10,
    french: "gênant",
    english: "annoying",
    spanish: "molesto",
  },
  {
    lesson: 10,
    french: "s'assurer de",
    english: "to assure oneself of",
    spanish: "asegurarse de",
  },
  {
    lesson: 10,
    french: "etonné",
    english: "astonished",
    spanish: "asombrado",
  },
  {
    lesson: 10,
    french: "prier",
    english: "to pray",
    spanish: "rogar/rezar",
  },
  {
    lesson: 10,
    french: "doute",
    english: "doubt",
    spanish: "duda",
  },
  {
    lesson: 10,
    french: "reconnaissant",
    english: "grateful",
    spanish: "agradecido",
  },
  {
    lesson: 10,
    french: "hâte",
    english: "haste",
    spanish: "prisa",
  },
  {
    lesson: 10,
    french: "lequel",
    english: "which",
    spanish: "el cual",
  },
  {
    lesson: 10,
    french: "dommage",
    english: "shame",
    spanish: "lástima",
  },
  {
    lesson: 10,
    french: "fous",
    english: "crazy",
    spanish: "loco",
  },
  {
    lesson: 10,
    french: "je m'en fous",
    english: "I do not care",
    spanish: "no me importa",
  },
  {
    lesson: 10,
    french: "séjour",
    english: "stay",
    spanish: "estadia",
  },
  {
    lesson: 10,
    french: "siège",
    english: "seat",
    spanish: "asiento",
  },
  {
    lesson: 10,
    french: "tromper",
    english: "to deceive",
    spanish: "engañar",
  },
  {
    lesson: 10,
    french: "énervant",
    english: "annoying",
    spanish: "irritante",
  },
  {
    lesson: 10,
    french: "gentiment",
    english: "kindly",
    spanish: "gentilmente",
  },
  {
    lesson: 10,
    french: "tu fais la por",
    english: "you do the job",
    spanish: "tu haces el trabajo",
  },
  {
    lesson: 10,
    french: "revue",
    english: "review/magazine",
    spanish: "revista",
  },
  {
    lesson: 10,
    french: "ravie",
    english: "delighted",
    spanish: "contento",
  },
  {
    lesson: 10,
    french: "recontrer",
    english: "meet",
    spanish: "encontrarse",
  },
];
