var lesson12 = [
  {
    lesson: 12,
    french: "comptable",
    english: "accountant",
    spanish: "contador",
  },
  {
    lesson: 12,
    french: "garde du corps",
    english: "bodyguard",
    spanish: "guardaespaldas",
  },
  {
    lesson: 12,
    french: "boucher",
    english: "butcher",
    spanish: "carnicero",
  },
  {
    lesson: 12,
    french: "charpentier",
    english: "carpenter",
    spanish: "carpintero",
  },
  {
    lesson: 12,
    french: "coursier",
    english: "courier",
    spanish: "mensajero",
  },
  {
    lesson: 12,
    french: "dessinateur",
    english: "designer",
    spanish: "diseñador",
  },
  {
    lesson: 12,
    french: "plongeur",
    english: "diver",
    spanish: "buzo",
  },
  {
    lesson: 12,
    french: "cadre",
    english: "executive/frame",
    spanish: "ejecutivo/marco",
  },
  {
    lesson: 12,
    french: "paysan",
    english: "peasant",
    spanish: "campesino",
  },
  {
    lesson: 12,
    french: "pompier",
    english: "firefighter",
    spanish: "bombero",
  },
  {
    lesson: 12,
    french: "pêcheur",
    english: "fisherman",
    spanish: "pescador",
  },
  {
    lesson: 12,
    french: "ouvrier",
    english: "worker",
    spanish: "obrero",
  },
  {
    lesson: 12,
    french: "epicier",
    english: "grocer",
    spanish: "tendero",
  },
  {
    lesson: 12,
    french: "coiffeur",
    english: "hairdresser",
    spanish: "peluquero",
  },
  {
    lesson: 12,
    french: "bijoutier",
    english: "jeweler",
    spanish: "joyero",
  },
  {
    lesson: 12,
    french: "sauveteur",
    english: "rescuer",
    spanish: "salvavidas",
  },
  {
    lesson: 12,
    french: "serrurier",
    english: "locksmith",
    spanish: "cerrajero",
  },
  {
    lesson: 12,
    french: "blacksmith",
    english: "forgeron/forgeronne",
    spanish: "herrero/a",
  },
  {
    lesson: 12,
    french: "mannequin",
    english: "model",
    spanish: "modelo",
  },
  {
    lesson: 12,
    french: "infirmière",
    english: "nurse",
    spanish: "enfermera",
  },
  {
    lesson: 12,
    french: "opticien",
    english: "optician",
    spanish: "optómetra",
  },
  {
    lesson: 12,
    french: "peintre",
    english: "painter",
    spanish: "pintor",
  },
  {
    lesson: 12,
    french: "plombier",
    english: "plumber",
    spanish: "plomero",
  },
  {
    lesson: 12,
    french: "prêtre",
    english: "priest",
    spanish: "sacerdote",
  },
  {
    lesson: 12,
    french: "matelot/marin",
    english: "sailor",
    spanish: "marinero",
  },
  {
    lesson: 12,
    french: "gardien/gardienne",
    english: "guardian",
    spanish: "guardian/celador",
  },
  {
    lesson: 12,
    french: "chirurgien",
    english: "surgeon",
    spanish: "cirujano",
  },
  {
    lesson: 12,
    french: "tailleur",
    english: "tailor",
    spanish: "sastre",
  },
  {
    lesson: 12,
    french: "maître",
    english: "master",
    spanish: "maestro",
  },
  {
    lesson: 12,
    french: "caissier",
    english: "cashier",
    spanish: "cajero",
  },
  {
    lesson: 12,
    french: "écrivain",
    english: "writer",
    spanish: "escritor",
  },
  {
    lesson: 12,
    french: "resoudre",
    english: "to solve",
    spanish: "resolver",
  },
  {
    lesson: 12,
    french: "étoiles",
    english: "stars",
    spanish: "estrellas",
  },
  {
    lesson: 12,
    french: "chemie",
    english: "chemistry",
    spanish: "química",
  },
  {
    lesson: 12,
    french: "élégir",
    english: "elect",
    spanish: "elegir",
  },
  {
    lesson: 12,
    french: "noyer",
    english: "to drown",
    spanish: "ahogar",
  },
  {
    lesson: 12,
    french: "du à",
    english: "due to",
    spanish: "debido a ",
  },
  {
    lesson: 12,
    french: "tondre",
    english: "mow",
    spanish: "cortar (céspedes)",
  },
  {
    lesson: 12,
    french: "gazon",
    english: "grass",
    spanish: "césped",
  },
  {
    lesson: 12,
    french: "endroit",
    english: "place",
    spanish: "lugar",
  },
  {
    lesson: 12,
    french: "",
    english: "",
    spanish: "",
  },
  {
    lesson: 12,
    french: "",
    english: "",
    spanish: "",
  },
  {
    lesson: 12,
    french: "",
    english: "",
    spanish: "",
  },
  {
    lesson: 12,
    french: "",
    english: "",
    spanish: "",
  },
  {
    lesson: 12,
    french: "",
    english: "",
    spanish: "",
  },
  {
    lesson: 12,
    french: "",
    english: "",
    spanish: "",
  },
  {
    lesson: 12,
    french: "",
    english: "",
    spanish: "",
  },

  {
    lesson: 12,
    french: "",
    english: "",
    spanish: "",
  },
  {
    lesson: 12,
    french: "",
    english: "",
    spanish: "",
  },
  {
    lesson: 12,
    french: "",
    english: "",
    spanish: "",
  },
  {
    lesson: 12,
    french: "",
    english: "",
    spanish: "",
  },
];
