var lesson16 = [
  {
    lesson: 16,
    french: "anorak",
    english: "anorak",
    spanish: "chaqueta de invierno",
  },
  {
    lesson: 16,
    french: "tablier",
    english: "apron",
    spanish: "delantal",
  },
  { lesson: 16, french: "béret", english: "beret", spanish: "boina" },
  {
    lesson: 16,
    french: "bonnet de bain",
    english: "bathing cap",
    spanish: "gorro de baño",
  },
  {
    lesson: 16,
    french: "maillot de bain",
    english: "swimsuit",
    spanish: "vestido de baño",
  },
  {
    lesson: 16,
    french: "robe de chambre",
    english: "dressing gown",
    spanish: "bata",
  },
  {
    lesson: 16,
    french: "ceinture",
    english: "belt",
    spanish: "cinturón",
  },
  {
    lesson: 16,
    french: "bermuda",
    english: "shorts",
    spanish: "bermudas",
  },
  {
    lesson: 16,
    french: "veste",
    english: "jacket",
    spanish: "chaqueta",
  },
  { lesson: 16, french: "blouse", english: "blouse", spanish: "blusa" },
  { lesson: 16, french: "bottes", english: "boots", spanish: "botas" },
  {
    lesson: 16,
    french: "noeud papillon",
    english: "bow tie",
    spanish: "corbatín",
  },
  {
    lesson: 16,
    french: "soutien-gorge",
    english: "bra",
    spanish: "brasier",
  },
  {
    lesson: 16,
    french: "bretelle",
    english: "suspenders",
    spanish: "tiranta",
  },
  {
    lesson: 16,
    french: "boucle",
    english: "buckle",
    spanish: "hebilla",
  },
  { lesson: 16, french: "bouton", english: "button", spanish: "botón" },
  {
    lesson: 16,
    french: "bonnet",
    english: "women cap",
    spanish: "gorro mujer",
  },
  { lesson: 16, french: "cape", english: "cape", spanish: "capa" },
  {
    lesson: 16,
    french: "daim",
    english: "ante",
    spanish: "ante/gamuza",
  },
  { lesson: 16, french: "gaze", english: "gaze", spanish: "gaza" },
  { lesson: 16, french: "manteau", english: "coat", spanish: "abrigo" },
  {
    lesson: 16,
    french: "collier",
    english: "necklace",
    spanish: "collar",
  },
  { lesson: 16, french: "col", english: "collar", spanish: "collar" },
  {
    lesson: 16,
    french: "coleurs",
    english: "colors",
    spanish: "colores",
  },
  {
    lesson: 16,
    french: "velours côtelé",
    english: "corduroy",
    spanish: "pana",
  },
  {
    lesson: 16,
    french: "coton",
    english: "cotton",
    spanish: "algodón",
  },
  {
    lesson: 16,
    french: "manchette/manche",
    english: "sleeve",
    spanish: "manga,puño de camisa",
  },
  {
    lesson: 16,
    french: "boutons de manchette",
    english: "cufflinks",
    spanish: "mancuernas",
  },
  {
    lesson: 16,
    french: "col rond",
    english: "round collar",
    spanish: "cuello redondo",
  },
  {
    lesson: 16,
    french: "smoking",
    english: "smoking",
    spanish: "esmoquin",
  },
  { lesson: 16, french: "robe", english: "dress", spanish: "vestido" },
  {
    lesson: 16,
    french: "broder",
    english: "border",
    spanish: "bordar",
  },
  {
    lesson: 16,
    french: "robe de nuit",
    english: "night gown",
    spanish: "traje de noche",
  },
  {
    lesson: 16,
    french: "éventail",
    english: "fan",
    spanish: "abanico",
  },
  {
    lesson: 16,
    french: "flanel",
    english: "flannel",
    spanish: "franela",
  },
  {
    lesson: 16,
    french: "bien aller",
    english: "to go well",
    spanish: "quedar bien",
  },
  {
    lesson: 16,
    french: "fourrure",
    english: "fur",
    spanish: "pelo animal",
  },
  {
    lesson: 16,
    french: "manteau de fourrure",
    english: "fur coat",
    spanish: "abrigo de piel",
  },
  {
    lesson: 16,
    french: "gants",
    english: "gloves",
    spanish: "guantes",
  },
  {
    lesson: 16,
    french: "sac à main",
    english: "purse",
    spanish: "cartera",
  },
  {
    lesson: 16,
    french: "mouchoir",
    english: "handkerchier",
    spanish: "pañuelo",
  },
  {
    lesson: 16,
    french: "fail à la mian",
    english: "handmade",
    spanish: "hecho a mano",
  },
  {
    lesson: 16,
    french: "chapeau",
    english: "hat",
    spanish: "sombrero",
  },
  {
    lesson: 16,
    french: "ourlet",
    english: "hem",
    spanish: "dobladillo",
  },
  {
    lesson: 16,
    french: "capuche",
    english: "hoodie",
    spanish: "capucha",
  },
  { lesson: 16, french: "cuir", english: "leather", spanish: "cuero" },
  { lesson: 16, french: "lin", english: "linen", spanish: "lino" },
  {
    lesson: 16,
    french: "doublure",
    english: "lining",
    spanish: "forro",
  },
  {
    lesson: 16,
    french: "manche longue",
    english: "long sleeve",
    spanish: "manga larga",
  },
  { lesson: 16, french: "laine", english: "wool", spanish: "lana" },
  {
    lesson: 16,
    french: "aiguille",
    english: "needle",
    spanish: "aguja",
  },
  {
    lesson: 16,
    french: "chemise de nuit",
    english: "nightdress",
    spanish: "camisa de dormir",
  },
  {
    lesson: 16,
    french: "ensemble",
    english: "together",
    spanish: "conjunto",
  },
  {
    lesson: 16,
    french: "pardessus",
    english: "overcoat",
    spanish: "sobretodo",
  },
  {
    lesson: 16,
    french: "épingles",
    english: "pins",
    spanish: "alfiler",
  },
  {
    lesson: 16,
    french: "poche",
    english: "pocket",
    spanish: "bolsillos",
  },
  { lesson: 16, french: "sac", english: "bag", spanish: "bolsa" },
  { lesson: 16, french: "gaze", english: "gaze", spanish: "gaza" },
  {
    lesson: 16,
    french: "ruban",
    english: "ribbon",
    spanish: "cinta regalos",
  },
  {
    lesson: 16,
    french: "ruban adhésif",
    english: "tape",
    spanish: "cinta adhesiva",
  },
  {
    lesson: 16,
    french: "Caoutchouc",
    english: "rubber",
    spanish: "caucho",
  },
  {
    lesson: 16,
    french: "sandales",
    english: "sandals",
    spanish: "sandalias",
  },
  {
    lesson: 16,
    french: "écharpe",
    english: "scarf",
    spanish: "bufanda",
  },
  { lesson: 16, french: "coudre", english: "to sew", spanish: "coser" },
  {
    lesson: 16,
    french: "chemise",
    english: "shirt",
    spanish: "camisa",
  },
  {
    lesson: 16,
    french: "chaussures",
    english: "shoes",
    spanish: "zapatas",
  },
  {
    lesson: 16,
    french: "court/e",
    english: "short",
    spanish: "corto/a",
  },
  { lesson: 16, french: "soie", english: "silk", spanish: "seda" },
  { lesson: 16, french: "jupe", english: "skirt", spanish: "falda" },
  {
    lesson: 16,
    french: "combinaison",
    english: "combination",
    spanish: "combinación",
  },
  {
    lesson: 16,
    french: "pantoufle",
    english: "slipper",
    spanish: "pantufla",
  },
  {
    lesson: 16,
    french: "chaussettes",
    english: "socks",
    spanish: "medias",
  },
  { lesson: 16, french: "canne", english: "cane", spanish: "bastón" },
  {
    lesson: 16,
    french: "costume",
    english: "suit",
    spanish: "traje de hombre",
  },
  {
    lesson: 16,
    french: "jarretière",
    english: "garter",
    spanish: "liguero",
  },
  {
    lesson: 16,
    french: "pull-over",
    english: "sweater",
    spanish: "saco",
  },
  { lesson: 16, french: "fil", english: "thread", spanish: "hilo" },
  { lesson: 16, french: "cravate", english: "tie", spanish: "corbata" },
  {
    lesson: 16,
    french: "serviette",
    english: "napkin/towel",
    spanish: "toalla/servilleta",
  },
  {
    lesson: 16,
    french: "peluche",
    english: "stuffed tow",
    spanish: "felpa",
  },
  {
    lesson: 16,
    french: "parapluie",
    english: "umbrella",
    spanish: "paraguas",
  },
  {
    lesson: 16,
    french: "ombrelle",
    english: "umbrella",
    spanish: "sombrilla",
  },
  { lesson: 16, french: "caleçon", english: "boxer", spanish: "boxer" },
  {
    lesson: 16,
    french: "velours",
    english: "velvet",
    spanish: "terciopelo",
  },
  { lesson: 16, french: "gilet", english: "vest", spanish: "chaleco" },
  {
    lesson: 16,
    french: "fermeture éclair",
    english: "zipper",
    spanish: "cremallera",
  },
];
