var lesson2 = [
  {
    lesson: 3,
    french: "époque",
    english: "era/age",
    spanish: "epoca/era",
  },
  {
    lesson: 3,
    french: "minuit",
    english: "midnight",
    spanish: "media noche",
  },
  {
    lesson: 3,
    french: "midi",
    english: "mid day",
    spanish: "medio día",
  },
  {
    lesson: 3,
    french: "crépuscule",
    english: "twilight",
    spanish: "crepúsculo",
  },
  {
    lesson: 3,
    french: "lever du soleil",
    english: "sunrise",
    spanish: "amanecer",
  },
  {
    lesson: 3,
    french: "coucher de soleil",
    english: "sunset",
    spanish: "atardecer",
  },

  {
    lesson: 3,
    french: "la veille",
    english: "eve",
    spanish: "víspera",
  },
  {
    lesson: 3,
    french: "journalier",
    english: "daily",
    spanish: "a diario",
  },
  {
    lesson: 3,
    french: "ancien",
    english: "ancient",
    spanish: "antiguo",
  },
  {
    lesson: 3,
    french: "ère christienne",
    english: "christan era",
    spanish: "era cristiana",
  },
  {
    lesson: 3,
    french: "Moyen âge",
    english: "Middle Age",
    spanish: "Edad Media",
  },
  {
    lesson: 3,
    french: "calendrier",
    english: "calendar",
    spanish: "calendario",
  },
  {
    lesson: 3,
    french: "foie",
    english: "faith",
    spanish: "fe",
  },
  {
    lesson: 3,
    french: "siècle",
    english: "century",
    spanish: "siglo",
  },
  {
    lesson: 3,
    french: "férié",
    english: "holiday",
    spanish: "feriado",
  },
  {
    lesson: 3,
    french: "antiquité",
    english: "antiquity",
    spanish: "antigüedad",
  },
  {
    lesson: 3,
    french: "complexe",
    english: "complex",
    spanish: "complejo",
  },
  {
    lesson: 3,
    french: "bruler",
    english: "to burn",
    spanish: "quemar",
  },
  {
    lesson: 3,
    french: "petit matin",
    english: "early morning",
    spanish: "temprano en la mañana",
  },
  {
    lesson: 3,
    french: "tâche",
    english: "task",
    spanish: "tarea",
  },
  {
    lesson: 3,
    french: "prière",
    english: "prayer",
    spanish: "oración",
  },
  {
    lesson: 3,
    french: "rassembler",
    english: "to gather",
    spanish: "reunirse",
  },
  {
    lesson: 3,
    french: "suite",
    english: "following",
    spanish: "siguiente",
  },
  {
    lesson: 3,
    french: "consommation",
    english: "consumption",
    spanish: "consumo",
  },
];
