var lesson14 = [
  {
    lesson: 14,
    french: "fourmi",
    english: "ant",
    spanish: "hormiga",
  },
  {
    lesson: 14,
    french: "ours fourmillier",
    english: "anteater bear",
    spanish: "oso hormiguero",
  },
  {
    lesson: 14,
    french: "tatou",
    english: "armadillo",
    spanish: "armadillo",
  },
  {
    lesson: 14,
    french: "chauve-souris",
    english: "bat",
    spanish: "murciélago",
  },
  {
    lesson: 14,
    french: "castor",
    english: "castor",
    spanish: "castor",
  },
  {
    lesson: 14,
    french: "abeille",
    english: "bee",
    spanish: "abeja",
  },

  {
    lesson: 14,
    french: "scarabée",
    english: "beetle",
    spanish: "escarabajo",
  },
  {
    lesson: 14,
    french: "oiseau",
    english: "bird",
    spanish: "pájaro",
  },
  {
    lesson: 14,
    french: "bison/ne",
    english: "bison",
    spanish: "bisonte",
  },
  {
    lesson: 14,
    french: "taureau",
    english: "bull",
    spanish: "toro",
  },
  {
    lesson: 14,
    french: "papillon",
    english: "butterfly",
    spanish: "mariposa",
  },
  {
    lesson: 14,
    french: "chameau",
    english: "camel",
    spanish: "camello",
  },
  {
    lesson: 14,
    french: "veau",
    english: "calf",
    spanish: "ternero",
  },
  {
    lesson: 14,
    french: "chenille",
    english: "caterpillar",
    spanish: "oruga",
  },
  {
    lesson: 14,
    french: "poussin",
    english: "chick",
    spanish: "pollito",
  },

  {
    lesson: 14,
    french: "poulet",
    english: "chicken",
    spanish: "pollo",
  },
  {
    lesson: 14,
    french: "chimpanzé",
    english: "chimpanzee",
    spanish: "chimpancé",
  },
  {
    lesson: 14,
    french: "coq",
    english: "cock",
    spanish: "gallo",
  },
  {
    lesson: 14,
    french: "crocodile",
    english: "crocodile",
    spanish: "cocodrilo",
  },
  {
    lesson: 14,
    french: "vache",
    english: "cow",
    spanish: "vaca",
  },

  {
    lesson: 14,
    french: "crabe",
    english: "crab",
    spanish: "cangrejo",
  },
  {
    lesson: 14,
    french: "cerf",
    english: "deer",
    spanish: "venado",
  },
  {
    lesson: 14,
    french: "âne",
    english: "donkey/ass",
    spanish: "asno",
  },
  {
    lesson: 14,
    french: "aigle",
    english: "eagle",
    spanish: "águila",
  },
  {
    lesson: 14,
    french: "éléphant",
    english: "elephant",
    spanish: "elefante",
  },
  {
    lesson: 14,
    french: "faon",
    english: "fawn",
    spanish: "cervatillo",
  },
  {
    lesson: 14,
    french: "poisson",
    english: "fish",
    spanish: "pez",
  },
  {
    lesson: 14,
    french: "mouche",
    english: "fly",
    spanish: "mosca",
  },
  {
    lesson: 14,
    french: "poulain",
    english: "colt",
    spanish: "potro",
  },
  {
    lesson: 14,
    french: "renard",
    english: "fox",
    spanish: "zorro",
  },

  {
    lesson: 14,
    french: "crapaud",
    english: "toad",
    spanish: "sapo",
  },
  {
    lesson: 14,
    french: "oies",
    english: "geese",
    spanish: "gansos",
  },
  {
    lesson: 14,
    french: "girafe",
    english: "girafe",
    spanish: "jirafa",
  },
  {
    lesson: 14,
    french: "chèvre",
    english: "goat",
    spanish: "cabra",
  },
  {
    lesson: 14,
    french: "taupe",
    english: "mole",
    spanish: "topo",
  },
  {
    lesson: 14,
    french: "gorille",
    english: "gorilla",
    spanish: "gorila",
  },

  {
    lesson: 14,
    french: "sauterelle",
    english: "grasshopper",
    spanish: "saltamontes",
  },
  {
    lesson: 14,
    french: "canard",
    english: "duck",
    spanish: "pato",
  },
  {
    lesson: 14,
    french: "faucon",
    english: "falcon",
    spanish: "halcón",
  },
  {
    lesson: 14,
    french: "poule",
    english: "hen",
    spanish: "gallina",
  },
  {
    lesson: 14,
    french: "hippopotame",
    english: "hippopotamus",
    spanish: "hipopótamo",
  },

  {
    lesson: 14,
    french: "cochon",
    english: "pig",
    spanish: "cerdo",
  },
  {
    lesson: 14,
    french: "cheval/chevaux (pluriel)",
    english: "horse",
    spanish: "caballo",
  },
  {
    lesson: 14,
    french: "hyène",
    english: "hyena",
    spanish: "hiena",
  },
  {
    lesson: 14,
    french: "insecte",
    english: "insect",
    spanish: "insecto",
  },

  {
    lesson: 14,
    french: "iguane",
    english: "iguana",
    spanish: "iguana",
  },
  {
    lesson: 14,
    french: "kangarou",
    english: "kangarou",
    spanish: "canguro",
  },
  {
    lesson: 14,
    french: "cocinelle",
    english: "ladybug",
    spanish: "mariquita",
  },
  {
    lesson: 14,
    french: "agneau",
    english: "lamb",
    spanish: "cordero",
  },
  {
    lesson: 14,
    french: "lézard",
    english: "lizard",
    spanish: "lagartija",
  },

  {
    lesson: 14,
    french: "lama",
    english: "lama",
    spanish: "llama",
  },
  {
    lesson: 14,
    french: "homard",
    english: "lobster",
    spanish: "langosta",
  },{
    lesson: 14,
    french: "mammifères",
    english: "mammals",
    spanish: "mamíferos",
  },
  {
    lesson: 14,
    french: "singe",
    english: "monkey",
    spanish: "mico",
  },
  {
    lesson: 14,
    french: "mite",
    english: "moth",
    spanish: "polilla",
  },
  {
    lesson: 14,
    french: "souris",
    english: "mouse",
    spanish: "ratón",
  },
  {
    lesson: 14,
    french: "orang-outan",
    english: "orangutan",
    spanish: "orangután",
  },
  {
    lesson: 14,
    french: "loutre",
    english: "otter",
    spanish: "nutria",
  },
  {
    lesson: 14,
    french: "chouette",
    english: "owl",
    spanish: "buho",
  },
  {
    lesson: 14,
    french: "boeuf",
    english: "ox",
    spanish: "buey",
  },
  {
    lesson: 14,
    french: "huîtres",
    english: "oysters/clams",
    spanish: "almejas",
  },

  {
    lesson: 14,
    french: "panda",
    english: "panda",
    spanish: "panda",
  },
  {
    lesson: 14,
    french: "perroquet",
    english: "parrot",
    spanish: "loro",
  },
  {
    lesson: 14,
    french: "paon",
    english: "peacock",
    spanish: "pavo real",
  },
  {
    lesson: 14,
    french: "pingouin",
    english: "penguin",
    spanish: "pingüino",
  },
  {
    lesson: 14,
    french: "ara",
    english: "macaw",
    spanish: "guacamaya",
  },
  {
    lesson: 14,
    french: "poney",
    english: "pony",
    spanish: "poni",
  },
  {
    lesson: 14,
    french: "hérisson",
    english: "hedgehog",
    spanish: "erizo",
  },
  {
    lesson: 14,
    french: "porc-épic",
    english: "porcupine",
    spanish: "puercoespin",
  },
  {
    lesson: 14,
    french: "chiot",
    english: "puppy",
    spanish: "cachorro",
  },
  {
    lesson: 14,
    french: "chaton",
    english: "kitten",
    spanish: "gato cachorro",
  },
  {
    lesson: 14,
    french: "primates",
    english: "primates",
    spanish: "primates",
  },
  {
    lesson: 14,
    french: "lapin",
    english: "rabbit",
    spanish: "conejo",
  },
  {
    lesson: 14,
    french: "rat",
    english: "rat",
    spanish: "rata",
  },
  {
    lesson: 14,
    french: "rhinocéros",
    english: "rhinoceros",
    spanish: "rinoceronte",
  },
  {
    lesson: 14,
    french: "phoque",
    english: "seal",
    spanish: "foca",
  },
  {
    lesson: 14,
    french: "requin",
    english: "shark",
    spanish: "tiburón",
  },
  {
    lesson: 14,
    french: "mouton",
    english: "sheep",
    spanish: "oveja (masculino)",
  },
  {
    lesson: 14,
    french: "crevette",
    english: "shrimp",
    spanish: "camarón",
  },
  {
    lesson: 14,
    french: "moufette",
    english: "skunk",
    spanish: "zorrillo/mofeta",
  },

  {
    lesson: 14,
    french: "escargot",
    english: "snail",
    spanish: "caracol",
  },
  {
    lesson: 14,
    french: "serpent",
    english: "snake",
    spanish: "serpiente",
  },
  {
    lesson: 14,
    french: "araignée",
    english: "spider",
    spanish: "araña",
  },
  {
    lesson: 14,
    french: "écureuil",
    english: "squirrel",
    spanish: "ardilla",
  },
  {
    lesson: 14,
    french: "dinde/dindon",
    english: "turkey",
    spanish: "pavo",
  },
  {
    lesson: 14,
    french: "tortue",
    english: "turttle",
    spanish: "tortuga",
  },
  {
    lesson: 14,
    french: "morse",
    english: "morse",
    spanish: "morsa",
  },
  {
    lesson: 14,
    french: "baleine",
    english: "whale",
    spanish: "ballena",
  },
  {
    lesson: 14,
    french: "loup",
    english: "wolf",
    spanish: "lobo",
  },
  {
    lesson: 14,
    french: "zèbre",
    english: "zebra",
    spanish: "cebra",
  },

  {
    lesson: 14,
    french: "grenouille",
    english: "frog",
    spanish: "rana",
  },
  {
    lesson: 14,
    french: "dauphin",
    english: "dolphin",
    spanish: "delfín",
  },
  {
    lesson: 14,
    french: "hair",
    english: "hate",
    spanish: "odiar",
  },
  {
    lesson: 14,
    french: "détester",
    english: "hate",
    spanish: "detestar",
  },
  {
    lesson: 14,
    french: "bosse",
    english: "bump",
    spanish: "bulto/joroba",
  },
  {
    lesson: 14,
    french: "sauvage",
    english: "savage",
    spanish: "salvaje",
  },
  {
    lesson: 14,
    french: "brebis",
    english: "sheep",
    spanish: "oveja (femenino)",
  },
  {
    lesson: 14,
    french: "allaiter",
    english: "breast-feed",
    spanish: "amamantar",
  },

  {
    lesson: 14,
    french: "bois",
    english: "wood",
    spanish: "madera",
  },
  {
    lesson: 14,
    french: "cornes",
    english: "horns",
    spanish: "cuernos",
  },
  {
    lesson: 14,
    french: "hurler",
    english: "to howl",
    spanish: "aullar",
  },
  {
    lesson: 14,
    french: "subir",
    english: "suffer",
    spanish: "sufrir",
  },
  {
    lesson: 14,
    french: "graisse",
    english: "fat",
    spanish: "grasa",
  },
  {
    lesson: 14,
    french: "chaser",
    english: "to chase",
    spanish: "cazar",
  },
  {
    lesson: 14,
    french: "vautour",
    english: "vulture",
    spanish: "buitre",
  },
];
