var lesson15 = [
  {
    lesson: 15,
    french: "lard/lardons",
    english: "bacon",
    spanish: "tocino",
  },
  {
    lesson: 15,
    french: "orge",
    english: "barley",
    spanish: "cebada",
  },
  {
    lesson: 15,
    french: "bière",
    english: "beer",
    spanish: "cerveza",
  },
  {
    lesson: 15,
    french: "pain",
    english: "bread",
    spanish: "pan",
  },
  {
    lesson: 15,
    french: "beurre",
    english: "butter",
    spanish: "mantequilla",
  },
  {
    lesson: 15,
    french: "gâteau",
    english: "cake",
    spanish: "pastel",
  },
  {
    lesson: 15,
    french: "chaise",
    english: "chair",
    spanish: "silla",
  },
  {
    lesson: 15,
    french: "cidre",
    english: "cider",
    spanish: "sidra",
  },
  {
    lesson: 15,
    french: "beignet",
    english: "donut",
    spanish: "donut",
  },
  {
    lesson: 15,
    french: "fourchette",
    english: "fork",
    spanish: "tenedor",
  },
  {
    lesson: 15,
    french: "verre",
    english: "glass",
    spanish: "vaso",
  },
  {
    lesson: 15,
    french: "lièvre",
    english: "hare",
    spanish: "liebre",
  },
  {
    lesson: 15,
    french: "couteau",
    english: "knife",
    spanish: "cuchillo",
  },
  {
    lesson: 15,
    french: "allegée",
    english: "lightened",
    spanish: "aligerado",
  },
  {
    lesson: 15,
    french: "foie",
    english: "liver",
    spanish: "hígado",
  },
  {
    lesson: 15,
    french: "margarine",
    english: "margarine",
    spanish: "margarina",
  },
  {
    lesson: 15,
    french: "boulettes de viande",
    english: "meatballs",
    spanish: "albóndigas",
  },
  {
    lesson: 15,
    french: "vin mousseaux",
    english: "sparkling wine",
    spanish: "vino espumoso",
  },
  {
    lesson: 15,
    french: "moudarde",
    english: "mustard",
    spanish: "mostaza",
  },
  {
    lesson: 15,
    french: "serviette",
    english: "napkin/towel",
    spanish: "servilleta/toalla",
  },
  {
    lesson: 15,
    french: "avoine",
    english: "oatmeal",
    spanish: "avena",
  },
  {
    lesson: 15,
    french: "huile",
    english: "oil",
    spanish: "aceite",
  },
  {
    lesson: 15,
    french: "perdrix",
    english: "partridge",
    spanish: "perdiz",
  },
  {
    lesson: 15,
    french: "piment",
    english: "pepper",
    spanish: "pimienta",
  },
  {
    lesson: 15,
    french: "tarte",
    english: "tart",
    spanish: "torta",
  },
  {
    lesson: 15,
    french: "pigeon",
    english: "pigeon",
    spanish: "paloma",
  },
  {
    lesson: 15,
    french: "assiette",
    english: "dish",
    spanish: "plato",
  },
  {
    lesson: 15,
    french: "riz",
    english: "rice",
    spanish: "arroz",
  },
  {
    lesson: 15,
    french: "rhum",
    english: "rum",
    spanish: "ron",
  },
  {
    lesson: 15,
    french: "sel",
    english: "salt",
    spanish: "sal",
  },
  {
    lesson: 15,
    french: "saliére",
    english: "salt shaker",
    spanish: "salero",
  },
  {
    lesson: 15,
    french: "sauscisses",
    english: "sausages",
    spanish: "salchichas",
  },
  {
    lesson: 15,
    french: "cuillère",
    english: "spoon",
    spanish: "cuchara",
  },
  {
    lesson: 15,
    french: "nappe",
    english: "layer",
    spanish: "capa",
  },
  {
    lesson: 15,
    french: "vapeur",
    english: "steam",
    spanish: "vapor",
  },
  {
    lesson: 15,
    french: "ragoût",
    english: "stew",
    spanish: "estofado",
  },
  {
    lesson: 15,
    french: "nappe de tableau",
    english: "tablecloth",
    spanish: "manteles",
  },
  {
    lesson: 15,
    french: "thé",
    english: "tea",
    spanish: "té",
  },
  {
    lesson: 15,
    french: "épais",
    english: "thick",
    spanish: "espeso",
  },
  {
    lesson: 15,
    french: "cure-dents",
    english: "toothpick",
    spanish: "palillos",
  },
  {
    lesson: 15,
    french: "fil dentaire",
    english: "dental floss",
    spanish: "seda dental",
  },
  {
    lesson: 15,
    french: "plateau",
    english: "plateau/tray",
    spanish: "meseta/bandeja",
  },
  {
    lesson: 15,
    french: "tiède",
    english: "lukewarm",
    spanish: "tibio",
  },
  {
    lesson: 15,
    french: "blé",
    english: "wheat",
    spanish: "trigo",
  },
  {
    lesson: 15,
    french: "cap",
    english: "cape",
    spanish: "capa",
  },
  {
    lesson: 15,
    french: "en haut",
    english: "up",
    spanish: "arriba",
  },
  {
    lesson: 15,
    french: "bas",
    english: "down",
    spanish: "abajo",
  },
  {
    lesson: 15,
    french: "halte",
    english: "halt",
    spanish: "detener",
  },
  {
    lesson: 15,
    french: "aîné/e",
    english: "elder",
    spanish: "anciano/a",
  },
  {
    lesson: 15,
    french: "âgé/e",
    english: "elderly",
    spanish: "anciano/a",
  },
  {
    lesson: 15,
    french: "léger",
    english: "light",
    spanish: "ligero",
  },
  {
    lesson: 15,
    french: "fondre",
    english: "to melt",
    spanish: "derretir",
  },
  {
    lesson: 15,
    french: "coincre",
    english: "to stuck",
    spanish: "atascado",
  },
  {
    lesson: 15,
    french: "mélanger",
    english: "to mix",
    spanish: "mezclar",
  },
  {
    lesson: 15,
    french: "poivre",
    english: "pepper",
    spanish: "pimienta",
  },
  {
    lesson: 15,
    french: "tasse",
    english: "cup",
    spanish: "taza",
  },
  {
    lesson: 15,
    french: "épaissir",
    english: "thicken",
    spanish: "espesar",
  },
  {
    lesson: 15,
    french: "vanille",
    english: "vanilla",
    spanish: "vainilla",
  },
  {
    lesson: 15,
    french: "peser",
    english: "to weight",
    spanish: "pesar",
  },
  {
    lesson: 15,
    french: "lait frappé",
    english: "milkshake",
    spanish: "malteada",
  },
  {
    lesson: 15,
    french: "vers",
    english: "towards",
    spanish: "hacia",
  },
  {
    lesson: 15,
    french: "dresser",
    english: "to draw up",
    spanish: "prepar algo (ej. una mesa)",
  },
  {
    lesson: 15,
    french: "or",
    english: "gold",
    spanish: "oro",
  },
  {
    lesson: 15,
    french: "argent",
    english: "silver",
    spanish: "plata",
  },
  {
    lesson: 15,
    french: "crise cardiaque",
    english: "heart attack",
    spanish: "infarto",
  },
  {
    lesson: 15,
    french: "tant",
    english: "so many",
    spanish: "infarto",
  }
];
