var lesson7 = [
  {
    lesson: 7,
    french: "séjour/salon",
    english: "living room",
    spanish: "sala",
  },
  {
    lesson: 7,
    french: "salle à manger",
    english: "dining room",
    spanish: "comedor",
  },
  {
    lesson: 7,
    french: "buanderie",
    english: "laundry room",
    spanish: "patio de ropas",
  },
  {
    lesson: 7,
    french: "nettoyer/faire le ménage",
    english: "to clean/to do the housework",
    spanish: "limpiar/asear",
  },
  {
    lesson: 7,
    french: "nettoyer/faire le ménage",
    english: "to clean/to do the housework",
    spanish: "limpiar/asear",
  },
  {
    lesson: 7,
    french: "cuisiner/faire cuire/préparer",
    english: "to cook",
    spanish: "cocinar",
  },
  {
    lesson: 7,
    french: "foyer",
    english: "home",
    spanish: "hogar",
  },
  {
    lesson: 7,
    french: "aspirer",
    english: "to strive",
    spanish: "aspirar",
  },
  {
    lesson: 7,
    french: "repas",
    english: "meal",
    spanish: "comida",
  },
  {
    lesson: 7,
    french: "propre",
    english: "own/clean",
    spanish: "propio/limpio",
  },
  {
    lesson: 7,
    french: "moquette",
    english: "carpet",
    spanish: "alfombra",
  },
  {
    lesson: 7,
    french: "vaiselle",
    english: "dishes",
    spanish: "loza/platos/vajilla",
  },
  {
    lesson: 7,
    french: "à l'aise",
    english: "comfortable",
    spanish: "cómodo",
  },
  {
    lesson: 7,
    french: "mal à l'aise",
    english: "uncomfortable",
    spanish: "incómodo",
  },
  {
    lesson: 7,
    french: "sale",
    english: "dirty",
    spanish: "sucio",
  },
  {
    lesson: 7,
    french: "accueillante",
    english: "welcoming",
    spanish: "acogedor",
  },
  {
    lesson: 7,
    french: "confortable",
    english: "cozy",
    spanish: "acogedor",
  },
  {
    lesson: 7,
    french: "jouet",
    english: "toy",
    spanish: "juguete",
  },
  {
    lesson: 7,
    french: "sol",
    english: "floor",
    spanish: "suelo",
  },
  {
    lesson: 7,
    french: "canapé",
    english: "couch",
    spanish: "sofá",
  },
  {
    lesson: 7,
    french: "canapé",
    english: "couch",
    spanish: "sofá",
  },
  {
    lesson: 7,
    french: "aspirateur",
    english: "vacuum",
    spanish: "aspiradora",
  },
  {
    lesson: 7,
    french: "pour quoique",
    english: "for whatever",
    spanish: "para lo que sea",
  },
  {
    lesson: 7,
    french: "quoique",
    english: "thought",
    spanish: "aunque",
  },
  {
    lesson: 7,
    french: "étendre",
    english: "to extend",
    spanish: "extender",
  },
  {
    lesson: 7,
    french: "étendre le linge",
    english: "hang out the laundry",
    spanish: "tender la ropa",
  },
  {
    lesson: 7,
    french: "pauvre",
    english: "poor",
    spanish: "pobre",
  },
  {
    lesson: 7,
    french: "par lá",
    english: "over there",
    spanish: "por alli",
  },
  {
    lesson: 7,
    french: "pauvre",
    english: "poor",
    spanish: "pobre",
  },
  {
    lesson: 7,
    french: "dessus",
    english: "above",
    spanish: "arriba",
  },
  {
    lesson: 7,
    french: "dessous",
    english: "underneath",
    spanish: "debajo",
  },
  {
    lesson: 7,
    french: "dessus-dessous",
    english: "upside down",
    spanish: "Al revés",
  },
  {
    lesson: 7,
    french: "débarraser",
    english: "to get rid of",
    spanish: "deshacerse",
  },
];
