var lesson11 = [
  {
    lesson: 11,
    french: "tête",
    english: "head",
    spanish: "cabeza",
  },
  {
    lesson: 11,
    french: "cheveux",
    english: "hair",
    spanish: "cabello",
  },
  {
    lesson: 11,
    french: "visage",
    english: "face",
    spanish: "cara",
  },
  {
    lesson: 11,
    french: "barbe",
    english: "beard",
    spanish: "barba",
  },
  {
    lesson: 11,
    french: "moustache",
    english: "moustache",
    spanish: "bigote",
  },
  {
    lesson: 11,
    french: "bouche",
    english: "mouth",
    spanish: "boca",
  },
  {
    lesson: 11,
    french: "gencives",
    english: "gums",
    spanish: "encía",
  },
  {
    lesson: 11,
    french: "dent",
    english: "tooth",
    spanish: "diente",
  },
  {
    lesson: 11,
    french: "langue",
    english: "tongue",
    spanish: "lengua",
  },
  {
    lesson: 11,
    french: "lèvre",
    english: "lips",
    spanish: "labios",
  },
  {
    lesson: 11,
    french: "molaires",
    english: "molars",
    spanish: "molares/muelas",
  },
  {
    lesson: 11,
    french: "mâchoire",
    english: "jaw",
    spanish: "mandíbula",
  },
  {
    lesson: 11,
    french: "menton",
    english: "chin",
    spanish: "mentón",
  },
  {
    lesson: 11,
    french: "oreilles",
    english: "ears",
    spanish: "orejas",
  },
  {
    lesson: 11,
    french: "",
    english: "",
    spanish: "",
  },
  {
    lesson: 11,
    french: "nez",
    english: "nose",
    spanish: "nariz",
  },
  {
    lesson: 11,
    french: "yeux",
    english: "eyes",
    spanish: "ojos",
  },
  {
    lesson: 11,
    french: "pupille",
    english: "pupil",
    spanish: "pupila",
  },
  {
    lesson: 11,
    french: "paupières",
    english: "eyelids",
    spanish: "párpados",
  },
  {
    lesson: 11,
    french: "sourbrows",
    english: "eyelash",
    spanish: "cejas",
  },
  {
    lesson: 11,
    french: "e",
    english: "eyelashes",
    spanish: "pestañas",
  },
  {
    lesson: 11,
    french: "front",
    english: "forehead",
    spanish: "frente",
  },
  {
    lesson: 11,
    french: "cou",
    english: "neck",
    spanish: "cuello",
  },
  {
    lesson: 11,
    french: "",
    english: "",
    spanish: "",
  },
  {
    lesson: 11,
    french: "gorge",
    english: "throat",
    spanish: "garganta",
  },
  {
    lesson: 11,
    french: "joues",
    english: "cheeks",
    spanish: "mejillas",
  },
  {
    lesson: 11,
    french: "poitrine",
    english: "chest",
    spanish: "pecho",
  },
  {
    lesson: 11,
    french: "bras",
    english: "arm",
    spanish: "brazo",
  },
  {
    lesson: 11,
    french: "aisselle",
    english: "armpit",
    spanish: "axila",
  },
  {
    lesson: 11,
    french: "avant-bras",
    english: "forearm",
    spanish: "antebrazo",
  },
  {
    lesson: 11,
    french: "épaule",
    english: "shoulder",
    spanish: "hombro",
  },
  {
    lesson: 11,
    french: "coude",
    english: "elbow",
    spanish: "codo",
  },
  {
    lesson: 11,
    french: "poignet",
    english: "wrist",
    spanish: "muñeca",
  },
  {
    lesson: 11,
    french: "paume",
    english: "palm",
    spanish: "palma",
  },
  {
    lesson: 11,
    french: "jointures",
    english: "knuckles",
    spanish: "nudillos",
  },
  {
    lesson: 11,
    french: "main",
    english: "hand",
    spanish: "mano",
  },
  {
    lesson: 11,
    french: "doigt",
    english: "finger",
    spanish: "dedo",
  },
  {
    lesson: 11,
    french: "petit doigt",
    english: "little finger",
    spanish: "meñique",
  },
  {
    lesson: 11,
    french: "annulaire (doigt)",
    english: "annular",
    spanish: "anular",
  },
  {
    lesson: 11,
    french: "puoce",
    english: "thumb",
    spanish: "pulgar",
  },
  {
    lesson: 11,
    french: "ongles",
    english: "nails",
    spanish: "uñas",
  },
  {
    lesson: 11,
    french: "abdomen",
    english: "abdomen",
    spanish: "abdomen",
  },
  {
    lesson: 11,
    french: "estomac",
    english: "stomach",
    spanish: "estómago",
  },
  {
    lesson: 11,
    french: "taille",
    english: "size",
    spanish: "talla",
  },
  {
    lesson: 11,
    french: "nombril",
    english: "belly button",
    spanish: "ombligo",
  },
  {
    lesson: 11,
    french: "fesses",
    english: "buttocks",
    spanish: "nalgas",
  },
  {
    lesson: 11,
    french: "thorax",
    english: "thorax",
    spanish: "tórax",
  },
  {
    lesson: 11,
    french: "hanche",
    english: "hip",
    spanish: "caderas",
  },
  {
    lesson: 11,
    french: "côtes",
    english: "ribs",
    spanish: "costillas",
  },
  {
    lesson: 11,
    french: "colonne vértébrale",
    english: "spine",
    spanish: "columna vertical",
  },
  {
    lesson: 11,
    french: "dos",
    english: "back",
    spanish: "espalda",
  },
  {
    lesson: 11,
    french: "jambe",
    english: "leg",
    spanish: "peirna",
  },
  {
    lesson: 11,
    french: "cuisse",
    english: "thigh",
    spanish: "muslo",
  },
  {
    lesson: 11,
    french: "genou",
    english: "knee",
    spanish: "rodilla",
  },
  {
    lesson: 11,
    french: "cheville",
    english: "ankle",
    spanish: "tobillo",
  },
  {
    lesson: 11,
    french: "pied",
    english: "foot",
    spanish: "pie",
  },
  {
    lesson: 11,
    french: "talon",
    english: "heel",
    spanish: "talón",
  },
  {
    lesson: 11,
    french: "diogts de pied/orteils",
    english: "toes",
    spanish: "dedos de los pies",
  },
  {
    lesson: 11,
    french: "corps",
    english: "body",
    spanish: "cuerpo",
  },
  {
    lesson: 11,
    french: "coeur",
    english: "heart",
    spanish: "corazón",
  },
  {
    lesson: 11,
    french: "poumon",
    english: "lung",
    spanish: "pulmón",
  },
  {
    lesson: 11,
    french: "foie",
    english: "liver",
    spanish: "hígado",
  },
  {
    lesson: 11,
    french: "intestin",
    english: "intestine",
    spanish: "intestino",
  },
  {
    lesson: 11,
    french: "os",
    english: "bone",
    spanish: "hueso",
  },
  {
    lesson: 11,
    french: "muscle",
    english: "muscle",
    spanish: "músculo",
  },
  {
    lesson: 11,
    french: "vessie",
    english: "bladder",
    spanish: "vejiga",
  },
  {
    lesson: 11,
    french: "rein",
    english: "kidney",
    spanish: "riñon",
  },
  {
    lesson: 11,
    french: "veines",
    english: "veins",
    spanish: "venas",
  },
  {
    lesson: 11,
    french: "sang",
    english: "blood",
    spanish: "sangre",
  },
  {
    lesson: 11,
    french: "tronc",
    english: "trunk",
    spanish: "tronco",
  },
  {
    lesson: 11,
    french: "crâne",
    english: "skull",
    spanish: "craneo",
  },
  {
    lesson: 11,
    french: "cerveau",
    english: "brain",
    spanish: "cerebro",
  },
  {
    lesson: 11,
    french: "épine",
    english: "spine/thorn",
    spanish: "espina",
  },
  {
    lesson: 11,
    french: "rate",
    english: "spleen",
    spanish: "bazo",
  },
  {
    lesson: 11,
    french: "vue",
    english: "sight",
    spanish: "vista",
  },
  {
    lesson: 11,
    french: "goût",
    english: "taste",
    spanish: "gusto",
  },
  {
    lesson: 11,
    french: "toucher",
    english: "to touch",
    spanish: "tocar",
  },
  {
    lesson: 11,
    french: "odorat",
    english: "sense of smell",
    spanish: "olfato",
  },
  {
    lesson: 11,
    french: "fièvre",
    english: "fever",
    spanish: "fiebre",
  },
  {
    lesson: 11,
    french: "peau",
    english: "skin",
    spanish: "piel",
  },
  {
    lesson: 11,
    french: "sains",
    english: "healthy",
    spanish: "sano",
  },
  {
    lesson: 11,
    french: "abcès",
    english: "abscess",
    spanish: "abcesos",
  },
  {
    lesson: 11,
    french: "poids",
    english: "weight",
    spanish: "peso",
  },
  {
    lesson: 11,
    french: "tendre",
    english: "tender",
    spanish: "tierno",
  },
  {
    lesson: 11,
    french: "mesurer",
    english: "measure",
    spanish: "medir",
  },
  {
    lesson: 11,
    french: "par contre",
    english: "on the other hand/however",
    spanish: "sin embargo",
  },
  {
    lesson: 11,
    french: "cependant",
    english: "however",
    spanish: "sin embargo",
  },
  {
    lesson: 11,
    french: "relier",
    english: "relate/connect",
    spanish: "enlazar",
  },
];
