var lesson13 = [
  {
    lesson: 13,
    french: "maison",
    english: "house",
    spanish: "casa",
  },
  {
    lesson: 13,
    french: "porte",
    english: "door",
    spanish: "puerta",
  },
  {
    lesson: 13,
    french: "paratonerre",
    english: "lightning rod",
    spanish: "pararayos",
  },
  {
    lesson: 13,
    french: "sous-sol",
    english: "basement",
    spanish: "sótano",
  },
  {
    lesson: 13,
    french: "fauteuil",
    english: "armchair",
    spanish: "sillon",
  },
  {
    lesson: 13,
    french: "lampe",
    english: "lamp",
    spanish: "lámpara",
  },
  {
    lesson: 13,
    french: "étagère",
    english: "shelf",
    spanish: "estante/repisa",
  },
  {
    lesson: 13,
    french: "carrlage",
    english: "floor tile",
    spanish: "baldosin",
  },
  {
    lesson: 13,
    french: "rideaux",
    english: "curtains",
    spanish: "cortinas",
  },
  {
    lesson: 13,
    french: "cheminée",
    english: "chimney",
    spanish: "chimenea",
  },
  {
    lesson: 13,
    french: "briques",
    english: "bricks",
    spanish: "ladrillos",
  },
  {
    lesson: 13,
    french: "plafond",
    english: "ceiling",
    spanish: "techo",
  },
  {
    lesson: 13,
    french: "chaîne",
    english: "chaine",
    spanish: "cadena",
  },
  {
    lesson: 13,
    french: "Equipement de son",
    english: "stereo",
    spanish: "equipo de sonido",
  },
  {
    lesson: 13,
    french: "pierre",
    english: "rock",
    spanish: "piedra",
  },
  {
    lesson: 13,
    french: "coiffuse",
    english: "hairdresser",
    spanish: "tocador",
  },
  {
    lesson: 13,
    french: "placard/armoire",
    english: "cupboard/cabinet",
    spanish: "closet/armario",
  },
  {
    lesson: 13,
    french: "oreiller",
    english: "pillow",
    spanish: "almohada",
  },
  {
    lesson: 13,
    french: "coussin",
    english: "cushion",
    spanish: "cojín",
  },
  {
    lesson: 13,
    french: "couverture",
    english: "blanket",
    spanish: "cobija",
  },
  {
    lesson: 13,
    french: "cuvette",
    english: "basin",
    spanish: "valde",
  },

  {
    lesson: 13,
    french: "baignore",
    english: "bathtub",
    spanish: "tina de baño",
  },
  {
    lesson: 13,
    french: "douche",
    english: "shower",
    spanish: "ducha",
  },
  {
    lesson: 13,
    french: "lavabo",
    english: "washbasin",
    spanish: "lavamanos",
  },
  {
    lesson: 13,
    french: "cabinet/wc",
    english: "lavatory/toilet",
    spanish: "inodoro",
  },
  {
    lesson: 13,
    french: "robinet",
    english: "faucet",
    spanish: "grifo",
  },
  {
    lesson: 13,
    french: "déversoir",
    english: "weir",
    spanish: "desagüe",
  },
  {
    lesson: 13,
    french: "peinture",
    english: "painting",
    spanish: "pintura",
  },

  {
    lesson: 13,
    french: "tiroirs",
    english: "drawers",
    spanish: "cajones",
  },
  {
    lesson: 13,
    french: "mur",
    english: "wall",
    spanish: "muro",
  },

  {
    lesson: 13,
    french: "poêle à frire",
    english: "frying pan",
    spanish: "sartén",
  },
  {
    lesson: 13,
    french: "poêle",
    english: "pan",
    spanish: "caserola",
  },
  {
    lesson: 13,
    french: "cuisinière/fourneau",
    english: "stove",
    spanish: "estufa",
  },
  {
    lesson: 13,
    french: "four",
    english: "oven",
    spanish: "horno",
  },
  {
    lesson: 13,
    french: "mixeur",
    english: "blender",
    spanish: "liquadora",
  },
  {
    lesson: 13,
    french: "armoire",
    english: "cupboard",
    spanish: "armario",
  },
  {
    lesson: 13,
    french: "évier",
    english: "to sink/sink",
    spanish: "hundir/lavaplatos",
  },
  {
    lesson: 13,
    french: "lucarne",
    english: "skylight",
    spanish: "claraboya",
  },
  {
    lesson: 13,
    french: "poubelle",
    english: "garbage can",
    spanish: "basura",
  },
  {
    lesson: 13,
    french: "ordures",
    english: "garbage",
    spanish: "basura",
  },
  {
    lesson: 13,
    french: "grenier",
    english: "attic",
    spanish: "ático",
  },
  {
    lesson: 13,
    french: "machine à laver",
    english: "washing machine",
    spanish: "lavadora",
  },
  {
    lesson: 13,
    french: "séchoir",
    english: "dryer",
    spanish: "secador (mujer)",
  },
  {
    lesson: 13,
    french: "éteindre",
    english: "to turn off",
    spanish: "apagar",
  },
  {
    lesson: 13,
    french: "allumer/mettre en marche",
    english: "to turn on",
    spanish: "encender",
  },

  {
    lesson: 13,
    french: "ouefs",
    english: "eggs",
    spanish: "huevos",
  },
  {
    lesson: 13,
    french: "vase",
    english: "vase",
    spanish: "florero",
  },

  {
    lesson: 13,
    french: "casserole",
    english: "cooking pot",
    spanish: "olla",
  },
  {
    lesson: 13,
    french: "effroyable",
    english: "frightful",
    spanish: "atterador",
  },
  {
    lesson: 13,
    french: "séchoir a linge",
    english: "clothes dryer",
    spanish: "secadora de ropa",
  },
  {
    lesson: 13,
    french: "règle",
    english: "ruler",
    spanish: "regla",
  },
  {
    lesson: 13,
    french: "ciseaux",
    english: "scissors",
    spanish: "tijeras",
  },
  {
    lesson: 13,
    french: "miroir",
    english: "mirror",
    spanish: "espejo",
  },
  {
    lesson: 13,
    french: "déménager",
    english: "to relocate",
    spanish: "mudarse",
  },
  {
    lesson: 13,
    french: "manquer",
    english: "to miss",
    spanish: "faltar",
  },
  {
    lesson: 13,
    french: "rez-de-chaussée",
    english: "first floor",
    spanish: "primer piso",
  },
  {
    lesson: 13,
    french: "tapis",
    english: "carpet",
    spanish: "alfombra/tapete",
  },
  {
    lesson: 13,
    french: "arrière-cour",
    english: "backyard",
    spanish: "patio trasero",
  },
  {
    lesson: 13,
    french: "tomber",
    english: "to fall",
    spanish: "caer",
  },
  {
    lesson: 13,
    french: "au-dessus",
    english: "above",
    spanish: "encima",
  },
  {
    lesson: 13,
    french: "porte-fenêtre",
    english: "french window",
    spanish: "puertaventana",
  },
  {
    lesson: 13,
    french: "chauffage",
    english: "heater",
    spanish: "calefacción",
  },
  {
    lesson: 13,
    french: "",
    english: "",
    spanish: "",
  },
  {
    lesson: 13,
    french: "",
    english: "",
    spanish: "",
  },
  {
    lesson: 13,
    french: "",
    english: "",
    spanish: "",
  },
  {
    lesson: 13,
    french: "",
    english: "",
    spanish: "",
  },
  {
    lesson: 13,
    french: "",
    english: "",
    spanish: "",
  },
  {
    lesson: 13,
    french: "",
    english: "",
    spanish: "",
  },
];
