var random = [
  {
    lesson: "-",
    french: "tellement",
    english: "so, such",
    spanish: "semejante",
  },
  {
    lesson: "-",
    french: "même (adjectif)",
    english: "same/itself/very/exact/precise",
    spanish: "igual",
  },
  {
    lesson: "-",
    french: "même (adverb)",
    english: "even",
    spanish: "incluso",
  },
  {
    lesson: "-",
    french: "même si",
    english: "even if",
    spanish: "aunque",
  },
  {
    lesson: "-",
    french: "facteur",
    english: "postman",
    spanish: "cartero",
  },
  {
    lesson: "-",
    french: "chouette",
    english: "owl, cool",
    spanish: "buho, chevere",
  },
  { lesson: "-", french: "se rendre", english: "go", spanish: "ir" },
  {
    lesson: "-",
    french: "soutenir",
    english: "support",
    spanish: "sostener",
  },
  {
    lesson: "-",
    french: "falloir",
    english: "to need",
    spanish: "necesitar",
  },
  {
    lesson: "-",
    french: "garder",
    english: "to keep",
    spanish: "mantener",
  },
  { lesson: "-", french: "donner", english: "to give", spanish: "dar" },
  {
    lesson: "-",
    french: "étant donné",
    english: "given that",
    spanish: "puesto que, dado que",
  },
  {
    lesson: "-",
    french: "drôle",
    english: "funny",
    spanish: "chistoso",
  },
  {
    lesson: "-",
    french: "amusant",
    english: "amusing",
    spanish: "divertido",
  },
  {
    lesson: "-",
    french: "prix",
    english: "price",
    spanish: "premio, precio",
  },
  {
    lesson: "-",
    french: "asperger",
    english: "to sprinkle",
    spanish: "rociar",
  },
  {
    lesson: "-",
    french: "a bien profité de",
    english: "took adventage of",
    spanish: "sacar ventaja de",
  },
  {
    lesson: "-",
    french: "arroser",
    english: "to water",
    spanish: "regar",
  },
  {
    lesson: "-",
    french: "tuyau",
    english: "hose",
    spanish: "manguera",
  },
  {
    lesson: "-",
    french: "partie",
    english: "party, part",
    spanish: "parte, fiesta",
  },
  {
    lesson: "-",
    french: "debout",
    english: "upright",
    spanish: "vertical",
  },
  {
    lesson: "-",
    french: "bredouille",
    english: "empty-handed",
    spanish: "con las manos vacías",
  },
  {
    lesson: "-",
    french: "tenir",
    english: "to hold",
    spanish: "sostener",
  },
  {
    lesson: "-",
    french: "attraper",
    english: "to catch",
    spanish: "atrapar",
  },
  {
    lesson: "-",
    french: "parfois/quelquefois",
    english: "sometimes",
    spanish: "a veces",
  },
  {
    lesson: "-",
    french: "parfois même",
    english: "sometimes",
    spanish: "algunas veces",
  },
  {
    lesson: "-",
    french: "ailleur",
    english: "elsewhere",
    spanish: "en otra parte",
  },
  {
    lesson: "-",
    french: "empêcher",
    english: "to prevent",
    spanish: "evitar",
  },
  {
    lesson: "-",
    french: "chômage",
    english: "unemployment",
    spanish: "desempleo",
  },
  {
    lesson: "-",
    french: "reconvoquer",
    english: "to reconvene",
    spanish: "reconvocar",
  },
  {
    lesson: "-",
    french: "pillage",
    english: "to plunder",
    spanish: "saquear",
  },
  {
    lesson: "-",
    french: "tourner",
    english: "to pan out",
    spanish: "salir",
  },
  {
    lesson: "-",
    french: "frapper",
    english: "to hit",
    spanish: "golpear",
  },
  {
    lesson: "-",
    french: "grignoter",
    english: "nibble",
    spanish: "picar",
  },
  {
    lesson: "-",
    french: "usine",
    english: "factory",
    spanish: "fabrica",
  },
  {
    lesson: "-",
    french: "ennuyé",
    english: "bored",
    spanish: "aburrido",
  },
  {
    lesson: "-",
    french: "ennuyeuse",
    english: "boring",
    spanish: "aburrido",
  },
  {
    lesson: "-",
    french: "boniment",
    english: "spiel/twist",
    spanish: "rollo",
  },
  {
    lesson: "-",
    french: "afficher",
    english: "to display",
    spanish: "mostrar",
  },
  {
    lesson: "-",
    french: "pas de soucis",
    english: "no worries",
    spanish: "no hay problema",
  },
];
